# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:59:58+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Path

from models import (
    Format,
    Standarderror,
    VersionsPublishAnonPostRequest,
    VersionsPublishAnonPostResponse,
    VersionsVersionIdExportFormatGetResponse,
    VersionsVersionIdImportPutRequest,
    VersionsVersionIdImportPutResponse,
    VersionsVersionIdPublishPostResponse,
    VersionsVersionIdUnpublishPutResponse,
)

app = MCPProxy(
    contact={'x-twitter': 'stoplightio'},
    description='',
    title='Stoplight',
    version='api-v1',
    servers=[{'url': 'https://api.stoplight.io/v1'}],
)


@app.post(
    '/versions/publish/anon',
    description=""" Anonymously publish to API Docs.

This endpoint will take a JSON spec or a URL to a swagger or raml spec.

```
{
  "specData": {...}
}
```

or

```
{
  "url": "http://petstore.swagger.io/v2/swagger.json"
}
```

The spec will be published to api-docs.io anonymously, which means you will not be able to update or remove this documentation.

The response will contain a url to the published documentation.

```
{
  "url": "https://swagger-petstore.api-docs.io/v1.0.0"
}
```


The limitations of anonymous publishing
* Cannot update/remove the documentation
* Cannot choose the subdomain
* Cannot choose the version
* Cannot add theming """,
    tags=['version_control_operations'],
)
def p_o_s_t_versions_publish_anon(body: VersionsPublishAnonPostRequest = None):
    """
    Publish Anonymous
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/versions/{versionId}/export/{format}',
    description=""" Export a version to your choice of API specification.

### Allowed Formats:

- oas.json
- oas.yaml
- raml08.yaml
- raml10.yaml
- stoplight.json
- stoplight.yaml

The stoplight format actually returns OAS (Swagger 2) with x-stoplight annotations. If you are exporting with the intent on importing back into Stoplight, this export format preserves the most information.

### Example URL:

`https://api.stoplight.io/v1/versions/123/export/oas.json` """,
    tags=['version_control_operations'],
)
def g_e_t_versions_version_id_export_format(
    version_id: str = Path(..., alias='versionId'), format: Format = 'oas.json'
):
    """
    Export
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/versions/{versionId}/import',
    description=""" Import the given specification into an existing version. 

**Warning, this is a destructive action! Any resources present in both the existing version, and the specification being imported, will be overwritten.**

This endpoint is particularly useful when you manage a specification file (Swagger or RAML) outside of Stoplight, and want to keep your Stoplight API version up to date as that specification changes.

By default, a "merge" is performed when importing. If a resource exists in the specification that you are importing, and in the Stoplight API, the resource will be overwritten. If a resource exists in the Stoplight API, but not in the spefication that you are importing, the resource will be left alone (and not deleted).

You can include an optional `options` property in the request body, to indicate if you would like to perform more of a replacement (instead of a merge). The options are documented in full in the response definition below these notes.

Take this request + request body for example:

`PUT https://api.stoplight.io/v1/versions/123/import`
```json
{
  "url": "http://petstore.swagger.io/v2/swagger.json",
  "options": {
    "removeExtraEndpoints": true,
    "removeExtraSchemas": true
  }
}
```

This request will grab the swagger specification described at `http://petstore.swagger.io/v2/swagger.json`, and import it into the Stoplight API version with id `123`. Additionally, it will delete any existing endpoints or models that are not described in the petstore swagger being imported.

Instead of a URL, you can provide the actual specification to be imported, either as a string (in the case of YAML) or an object (in the case of JSON). That request would look something like this:

`PUT https://api.stoplight.io/v1/versions/123/import`
```json
{
  "specData": {
    "swagger": "2.0",
    "info": {}
    ... rest of spec
  }
}
``` """,
    tags=['version_control_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def p_u_t_versions_version_id_import(
    version_id: str = Path(..., alias='versionId'),
    body: VersionsVersionIdImportPutRequest = None,
):
    """
    Import
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/versions/{versionId}/publish',
    description=""" Re-publish an API version in Stoplight. This will re-publish the given API version, with whatever publish settings have already been setup in the app.

This will only work with APIs that have previously been published at least once.

This works well with the #endpoint:957qEfc97BB5XGAeZ endpoint to augment your continuous integration processes, and automatically re-publish your documentation when certain events happen. Once such scenario is:

1. Swagger is generated from your codebase, and pushed up to Github.
2. A simple script that you write sends a request to the Stoplight API to import the new specification, passing in the URL to the swagger file on Github.
3. After the import succeeds, and your API in Stoplight is up to date, the script sends a request to the Stoplight API (this endpoint) to re-publish your documentation. """,
    tags=['version_control_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def p_o_s_t_versions_version_id_publish(version_id: str = Path(..., alias='versionId')):
    """
    Publish
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/versions/{versionId}/unpublish',
    description=""" Unpublish the documentation associated with the given API version. """,
    tags=['version_control_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def p_u_t_versions_version_id_unpublish(version_id: str = Path(..., alias='versionId')):
    """
    Unpublish
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
