# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:59:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, Field, RootModel


class SharedUser(BaseModel):
    field_: Optional[str] = None
    username: Optional[str] = None


class Standarderror(RootModel[Any]):
    root: Any


class VersionsPublishAnonPostRequest(BaseModel):
    specData: Optional[Union[Dict[str, Any], str]] = None
    url: Optional[str] = None


class VersionsPublishAnonPostResponse(BaseModel):
    url: str


class VersionsVersionIdExportFormatGetResponse(RootModel[Union[Dict[str, Any], str]]):
    root: Union[Dict[str, Any], str] = Field(
        ...,
        description='The specification. Returned as a string when YAML, object when JSON.',
    )


class Format(Enum):
    oas_json = 'oas.json'
    oas_yaml = 'oas.yaml'
    raml08_yaml = 'raml08.yaml'
    raml10_yaml = 'raml10.yaml'
    stoplight_json = 'stoplight.json'
    stoplight_yaml = 'stoplight.yaml'


class Options(BaseModel):
    removeExtraEndpoints: Optional[bool] = Field('', description='Default: false.')
    removeExtraSchemas: Optional[bool] = Field('', description='Default: false.')
    removeExtraTextSections: Optional[bool] = Field('', description='Default: false.')
    removeExtraTraits: Optional[bool] = Field('', description='Default: false.')


class VersionsVersionIdImportPutRequest(BaseModel):
    options: Optional[Options] = None
    specData: Optional[Union[Dict[str, Any], str]] = None
    url: Optional[str] = None


class Format1(Enum):
    RAML08 = 'RAML08'
    RAML10 = 'RAML10'
    SWAGGER = 'SWAGGER'
    STOPLIGHTX = 'STOPLIGHTX'


class Data(BaseModel):
    endpointCount: float
    format: Format1
    projectId: str
    schemaCount: float
    testCount: float
    textSectionCount: float
    traitCount: float
    versionId: str
    workspaceId: str


class VersionsVersionIdImportPutResponse(BaseModel):
    data: Data


class VersionsVersionIdPublishPostResponse(BaseModel):
    customDomain: Optional[str] = None
    url: str


class VersionsVersionIdUnpublishPutResponse(BaseModel):
    data: Optional[Dict[str, Any]] = None
